version: "3.7"
services:
  mysql-database-service:
    image: "mysql"
    container_name: mysql-database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=quartz_demo
    restart: always
    ports:
      - 3307:3306
    volumes:
      - "./scripts/quartz_tables.sql:/docker-entrypoint-initdb.d/1.sql"

  spring-boot-scheduled-email-service:
    image: spring-boot-scheduled-email
    container_name: spring-boot-scheduled-email
    build: .
    ports:
      - 9080:8080
    restart: always
    depends_on:
      - mysql-database-service